version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
    - "8080:80"

  db:
    image: mysql:8.0
     # The cap_add set to SYS_NICE suppresses some not useful error messages.
    # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log/55706057#55706057
    cap_add:
      - SYS_NICE
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=$DATABASE
      - MYSQL_USER=$DBUSER
      - MYSQL_PASSWORD=$DBPASSWORD
      - MYSQL_ROOT_PASSWORD=$DBROOTPASSWORD
    ports: 
      - $DBPORT:$DBPORT
    volumes:
      - db:/var/lib/mysql
      - ./db/CreateDatabase.sql:/docker-entrypoint-initdb.d/CreateDatabase.sql
    depends_on:
      - nginx

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: on-failure
    env_file:
      - .env
    environment:
      - HOSTNAME=$HOSTNAME
      - PORT=$PORT
      - DATABASE=$DATABASE
      - DBUSER=$DBUSER
      - DBPASSWORD=$DBPASSWORD
      - DBROOTPASSWORD=$DBROOTPASSWORD
      - DBHOST=db
      - DBPORT=$DBPORT
    ports:
      - $PORT:$PORT
  
networks:
  default:
    driver: bridge

volumes:
  db:
    driver: local    
