version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
    - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
    - "8080:80"
    depends_on:
    - app
  
networks:
  default:
    driver: bridge

volumes:
  db:
    driver: local